# Conceitos básicos de NumPy
***

O NumPy é uma biblioteca do Python que é amplamente usada para análise de dados, especialmente quando se trabalha com matrizes e arrays multidimensionais. O NumPy oferece muitas funções para operações em arrays, como soma, subtração, multiplicação, divisão e muito mais.

### Importação da biblioteca

In [1]:
import numpy as np

### Criar um array NumPy simples

Em programação, um array é uma coleção de elementos do mesmo tipo, que são armazenados em uma sequência contígua na memória. Em outras palavras, é uma estrutura de dados que contém um conjunto de valores do mesmo tipo.

No NumPy, um array é um objeto multidimensional que pode conter elementos de diferentes tipos. Arrays NumPy são geralmente mais eficientes e poderosos do que listas do Python, pois permitem operações matemáticas eficientes em grande quantidade de dados.

In [2]:
array = np.array([1, 3, 4, 8])
print(array)

[1 3 4 8]


### Acessar os elementos em um array
Os índices em NumPy começam em 0. Por exemplo, para acessar o segundo elemento do array acima, você pode usar o índice 1,

In [3]:
# Acessar o segundo elemento do array
array[1]

3

In [4]:
# Acessar o último elemento do array
array[-1]

8

### Alterar o formato de um array 
 Nesse exemplo criamos um array unidimensional com seis elementos e, em seguida, o convertemos em um array bidimensional com duas linhas e três colunas:

In [5]:
arr = np.array([1,2,3,4,5,6])
new_array = arr.reshape(2,3)
print(f'{arr}\n {new_array}')

[1 2 3 4 5 6]
 [[1 2 3]
 [4 5 6]]


In [6]:
#Acessar o segundo elemento do array
new_array[0,1]

2

In [7]:
#Acessar o segundo elemento do array
new_array[-1,1]

5

### Operações aritméticas em arrays NumPy

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

resultado = arr1 + arr2
print(resultado)

[5 7 9]


In [9]:
resultado = arr1 * arr2
print(resultado)

[ 4 10 18]


In [11]:
matriz1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print(matriz1, '\n\n', matriz2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[9 8 7]
 [6 5 4]
 [3 2 1]]


In [13]:
resultado = matriz1 * matriz2
print(resultado)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]
