# Funções do NumPy
***

O NumPy possui diversas funções que facilitam a manipulação e análise de dados em arrays multidimensionais. Nesse notebook vamos demonstrar algumas delas. 

### Importação da biblioteca

In [1]:
import numpy as np

### np.arange()
Cria um array com valores sequenciais em um intervalo especificado;

In [2]:
# cria um array com valores sequenciais de 0 a 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.arange(0,11, 2)

array([ 0,  2,  4,  6,  8, 10])

### np.zeros()
Cria um array preenchido com zeros;

In [5]:
# cria um array com 3 elementos preenchidos com zeros
np.zeros(3)

array([0., 0., 0.])

In [9]:
a = np.zeros([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
type(a[0][0])

numpy.float64

### np.ones()
Cria um array preenchido com uns;

In [12]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

### np.eye()
Cria uma matriz identidade;

Uma matriz identidade é uma matriz quadrada em que todos os elementos da diagonal principal são iguais a 1 e todos os outros elementos são iguais a 0.

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.random.rand()
Gera um array com valores aleatórios entre 0 e 1.

In [21]:
# Gera um array de shape (2,3) com valores aleatórios entre 0 e 1
np.random.rand(2, 3)

array([[0.15051468, 0.33976482, 0.59263735],
       [0.79897314, 0.66122784, 0.42727207]])

### np.random.randn()
Gera um array com valores aleatórios seguindo uma distribuição normal.

In [22]:
# Gera um array de shape (3,4) com valores aleatórios seguindo uma distribuição normal
np.random.randn(3, 4)

array([[ 1.45379864, -2.01085995,  0.63630572, -0.12888439],
       [-2.42012386, -0.34060927, -1.08088151, -0.71074143],
       [ 1.08665241,  2.86615622, -2.59684149, -0.59066175]])

### np.reshape()
Modifica a forma de um array.

In [23]:
# Cria um array de shape (3,4)
arr = np.arange(12).reshape(2,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

### np.transpose()
Transpõe um array.

In [24]:
# Cria um array de shape (2,3)
np.transpose(arr)

array([[ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11]])

### np.concatenate()
Concatena arrays.

In [29]:
# Cria dois arrays de shape (2,2)
arr1 = np.arange(5)
arr2 = np.random.rand(5)
np.concatenate((arr1, arr2))

array([0.        , 1.        , 2.        , 3.        , 4.        ,
       0.74465238, 0.23340562, 0.47931399, 0.95447416, 0.63357204])

### np.split()
Divide um array em partes.

In [35]:
arr = np.array([1, 2, 3 ,4, 5, 6])
array_split = np.split(arr, 2)
array_split


[array([1, 2, 3]), array([4, 5, 6])]

In [36]:
type(array_split)

list

In [37]:
array_split[0]

array([1, 2, 3])

### np.max()
A função np.max() retorna o valor máximo de um array.

In [31]:
arr.max()

6

### np.min()
A função np.min() retorna o valor mínimo de um array.

In [32]:
arr.min()

1

### np.mean()
A função np.mean() retorna a média dos valores em um array.

In [33]:
arr.mean()

3.5

### np.std()
A função np.std() retorna o desvio padrão dos valores em um array.

In [34]:
arr.std()

1.707825127659933

### np.sum()
A função np.sum() retorna a soma dos valores em um array.

In [38]:
arr.sum()

21