# Análise de vendas
***

*Contexto*: 
   
Uma empresa de varejo acaba de abrir uma nova filial em uma cidade e está em fase de avaliação. Para isso, foram  escolhidos quatro produtos que estão sendo vendidos na loja e foi realizado um registro diário das vendas ao longo de uma semana. A intenção é utilizar o NumPy para analisar as vendas da semana, identificar padrões e tomar decisões estratégicas com base nos resultados.

Os dados foram coletados e armazenados em uma matriz 5x4, onde cada linha representa um dia da semana e cada coluna representa um produto. O objetivo é analisar a quantidade de produtos vendidos em cada dia da semana, identificar qual produto teve o melhor desempenho e qual teve o pior, além de calcular a média de vendas diárias e a variação entre os dias da semana. 

Axis = 1 (linha)
Axis = 0 (coluna)

### Importação da biblioteca

In [3]:
import numpy as np

In [7]:
# criação da matriz com as vendas da semana
vendas_semana = np.array([
    [12, 10, 8, 6], 
    [18, 15, 12, 10],
    [10, 8, 5, 3],
    [22, 20, 18, 16],
    [15, 12, 10, 8]
])

In [8]:
vendas_semana

array([[12, 10,  8,  6],
       [18, 15, 12, 10],
       [10,  8,  5,  3],
       [22, 20, 18, 16],
       [15, 12, 10,  8]])

### Qual o total de vendas em cada dia da semana?

In [9]:
vendas_semana.sum(axis=1)

array([36, 55, 26, 76, 45])

### Qual o total de vendas de cada produto?

In [10]:
vendas_semana.sum(axis=0)

array([77, 65, 53, 43])

### Qual a média de vendas por dia da semana?

In [11]:
vendas_semana.mean(axis=0)

array([15.4, 13. , 10.6,  8.6])

### Qual o produto com menor variação nas vendas ao longo da semana?

In [14]:
variacao = vendas_semana.std(axis=0)
min_variacao = variacao.argmin()

In [15]:
min_variacao+1

2

### Identificar o produto com maior e menor vendas na semana

In [18]:
maior_venda = vendas_semana.sum(axis=0).argmax()
menor_venda = vendas_semana.sum(axis=0).argmin()

print(f'''
      O produto com maior venda é: {maior_venda+1}
      O produto com menor venda é: {menor_venda+1}''')


      O produto com maior venda é: 1
      O produto com menor venda é: 4


In [19]:
vendas_semana.sum(axis=0)

array([77, 65, 53, 43])

### Calcular a média de vendas diárias e variação entre os dias da semana

In [20]:
vendas_semana.mean(axis=0)

array([15.4, 13. , 10.6,  8.6])